name: Code Security Scanning

on: 
  push:
  workflow_dispatch:

jobs:

  security-scanning:
    runs-on: ubuntu-latest
    name: Datadog Security Scanning
    steps:
      - name: install datadog-ci
        uses: DataDog/install-datadog-ci-github-action@v1
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: upload git metadata with datadog-ci
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_SITE: datadoghq.com
          DD_GIT_REPOSITORY_URL: "https://github.com/kennaskoczen/DAST-DSVW-pipeline-test"
          DD_GIT_BRANCH: ${{ github.ref_name }}
          DD_GIT_COMMIT_SHA: ${{ github.sha }}
        run: datadog-ci git-metadata upload
      - name: SCA Scanning
        id: datadog-software-composition-analysis
        uses: DataDog/datadog-sca-github-action@main
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_site: "datadoghq.com"
      - name: SAST/Secrets scanning
        id: datadog-static-analysis
        uses: DataDog/datadog-static-analyzer-github-action@v3
        with:
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_site: "datadoghq.com"
          secrets_enabled: true
          static_analysis_enabled: true
      - name: IaC Scanning
        id: datadog-iac-scan
        uses: DataDog/datadog-iac-scanner-github-action@v1
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_site: datadoghq.com