on: [push]

name: Datadog Static Code Analysis

jobs:
  datadog-ci-metadata-upload:
    runs-on: ubuntu-latest
    steps:
      - name: install datadog-ci
        uses: DataDog/install-datadog-ci-github-action@v1
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: upload git metadata with datadog-ci
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_SITE: datadoghq.com
          DD_GIT_REPOSITORY_URL: "https://github.com/kennaskoczen/DAST-DSVW-pipeline-test"
          DD_GIT_BRANCH: ${{ github.ref_name }}
          DD_GIT_COMMIT_SHA: ${{ github.sha }}
        run: datadog-ci git-metadata upload

  static-analysis:
    runs-on: ubuntu-latest
    needs: datadog-ci-metadata-upload
    name: Datadog Static Analyzer
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Check code meets quality and security standards
      id: datadog-static-analysis
      uses: DataDog/datadog-static-analyzer-github-action@v3
      with:
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
        DD_SITE: datadoghq.com
        secrets_enabled: false
        static_analysis_enabled: true
        cpu_count: 2
