name: Datadog IaC Scan
on: [push]

jobs:
  datadog-ci-metadata-upload:
    runs-on: ubuntu-latest
    steps:
      - name: install datadog-ci
        uses: DataDog/install-datadog-ci-github-action@v1
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags
      - name: upload git metadata with datadog-ci
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_SITE: datadoghq.com
        run: datadog-ci git-metadata upload

  datadog-iac-scan:
    runs-on: ubuntu-latest
    needs: datadog-ci-metadata-upload
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: DataDog/datadog-iac-scanner-github-action@v1
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_site: datadoghq.com
