name: Datadog IaC Scan
on: [push]

jobs:
  datadog-ci-metadata-upload:
    runs-on: ubuntu-latest
    steps:
      - name: install datadog-ci
        uses: DataDog/install-datadog-ci-github-action@v1
      - name: upload git metadata with datadog-ci
        run: datadog-ci git-metadata upload
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_site: datadoghq.com

  datadog-iac-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: DataDog/datadog-iac-scanner-github-action@v1
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_site: datadoghq.com
