on: [push]

name: Datadog Software Composition Analysis

jobs:
  datadog-ci-metadata-upload:
    runs-on: ubuntu-latest
    steps:
      - name: install datadog-ci
        uses: DataDog/install-datadog-ci-github-action@v1
      - name: upload git metadata with datadog-ci
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_site: datadoghq.com
        run: datadog-ci git-metadata upload

  software-composition-analysis:
    runs-on: ubuntu-latest
    name: Datadog SBOM Generation and Upload
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Check imported libraries are secure and compliant
      id: datadog-software-composition-analysis
      uses: DataDog/datadog-sca-github-action@main
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_site: datadoghq.com
