name: Datadog IaC Scan
on: [push]

jobs:
  datadog-ci-metadata-upload:
    runs-on: ubuntu-latest
    steps:
      - name: install datadog-ci
        uses: DataDog/install-datadog-ci-github-action@v1
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: upload git metadata with datadog-ci
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_SITE: datadoghq.com
          DD_GIT_REPOSITORY_URL: "https://github.com/kennaskoczen/DAST-DSVW-pipeline-test"
          DD_GIT_BRANCH: ${{ github.ref_name }}
          DD_GIT_COMMIT_SHA: ${{ github.sha }}
        run: datadog-ci git-metadata upload

  datadog-iac-scan:
    runs-on: ubuntu-latest
    needs: datadog-ci-metadata-upload
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: DataDog/datadog-iac-scanner-github-action@v1
      with:
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
        DD_SITE: datadoghq.com
