name: Deploy App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Clones your repository to the runner

      - name: Sync Files to EC2 via SSH
        uses: appleboy/scp-action@master # Securely copies your files over to EC2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.EC2_USER }}/DAST-DSVW-pipeline-test"

      - name: Restart Application on EC2
        uses: appleboy/ssh-action@master # Runs commands inside your EC2 terminal
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/DAST-DSVW-pipeline-test
            /home/${{ secrets.EC2_USER }}/DAST-DSVW-pipeline-test/scripts/application_start.sh
