jobs:
  datadog-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: upload git metadata
        env: 
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_SITE: 'datadoghq.com'
        run: npx @datadog/datadog-ci git-metadata upload
